chore(dev-deps): ⬆️ update devdependencies (non-major) (patch) (#26)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [prettier](https://prettier.io) ([source](https://togithub.com/prettier/prettier)) | [`^2.8.3` -> `^2.8.4`](https://renovatebot.com/diffs/npm/prettier/2.8.3/2.8.4) | [![age](https://badges.renovateapi.com/packages/npm/prettier/2.8.4/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.8.4/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/prettier/2.8.4/compatibility-slim/2.8.3)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.8.4/confidence-slim/2.8.3)](https://docs.renovatebot.com/merge-confidence/) |
| [turbo](https://turbo.build/repo) ([source](https://togithub.com/vercel/turbo)) | [`^1.7.3` -> `^1.7.4`](https://renovatebot.com/diffs/npm/turbo/1.7.3/1.7.4) | [![age](https://badges.renovateapi.com/packages/npm/turbo/1.7.4/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/turbo/1.7.4/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/turbo/1.7.4/compatibility-slim/1.7.3)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/turbo/1.7.4/confidence-slim/1.7.3)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>prettier/prettier</summary>

### [`v2.8.4`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;284)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.8.3...2.8.4)

[diff](https://togithub.com/prettier/prettier/compare/2.8.3...2.8.4)

##### Fix leading comments in mapped types with `readonly` ([#&#8203;13427](https://togithub.com/prettier/prettier/pull/13427) by [@&#8203;thorn0](https://togithub.com/thorn0), [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))



```tsx
// Input
type Type = {
  // comment
  readonly [key in Foo];
};

// Prettier 2.8.3
type Type = {
  readonly // comment
  [key in Foo];
};

// Prettier 2.8.4
type Type = {
  // comment
  readonly [key in Foo];
};
```

##### Group params in opening block statements ([#&#8203;14067](https://togithub.com/prettier/prettier/pull/14067) by [@&#8203;jamescdavis](https://togithub.com/jamescdavis))

This is a follow-up to [#&#8203;13930](https://togithub.com/prettier/prettier/issues/13930) to establish wrapping consistency between opening block statements and else blocks by
grouping params in opening blocks. This causes params to break to a new line together and not be split across lines
unless the length of params exceeds the print width. This also updates the else block wrapping to behave exactly the
same as opening blocks.



```hbs
{{! Input }}
{{#block param param param param param param param param param param as |blockParam|}}
  Hello
{{else block param param param param param param param param param param as |blockParam|}}
  There
{{/block}}

{{! Prettier 2.8.3 }}
{{#block
  param
  param
  param
  param
  param
  param
  param
  param
  param
  param
  as |blockParam|
}}
  Hello
{{else block param
param
param
param
param
param
param
param
param
param}}
  There
{{/block}}

{{! Prettier 2.8.4 }}
{{#block
  param param param param param param param param param param
  as |blockParam|
}}
  Hello
{{else block
  param param param param param param param param param param
  as |blockParam|
}}
  There
{{/block}}
```

##### Ignore files in `.sl/` ([#&#8203;14206](https://togithub.com/prettier/prettier/pull/14206) by [@&#8203;bolinfest](https://togithub.com/bolinfest))

In [Sapling SCM](https://sapling-scm.com/), `.sl/` is the folder where it stores its state, analogous to `.git/` in Git. It should be ignored in Prettier like the other SCM folders.

##### Recognize `@satisfies` in Closure-style type casts ([#&#8203;14262](https://togithub.com/prettier/prettier/pull/14262) by [@&#8203;fisker](https://togithub.com/fisker))



```jsx
// Input
const a = /** @&#8203;satisfies {Record<string, string>} */ ({hello: 1337});
const b = /** @&#8203;type {Record<string, string>} */ ({hello: 1337});

// Prettier 2.8.3
const a = /** @&#8203;satisfies {Record<string, string>} */ { hello: 1337 };
const b = /** @&#8203;type {Record<string, string>} */ ({ hello: 1337 });

// Prettier 2.8.4
const a = /** @&#8203;satisfies {Record<string, string>} */ ({hello: 1337});
const b = /** @&#8203;type {Record<string, string>} */ ({hello: 1337});
```

##### Fix parens in inferred function return types with `extends` ([#&#8203;14279](https://togithub.com/prettier/prettier/pull/14279) by [@&#8203;fisker](https://togithub.com/fisker))



```ts
// Input
type Foo<T> = T extends ((a) => a is infer R extends string) ? R : never;

// Prettier 2.8.3 (First format)
type Foo<T> = T extends (a) => a is infer R extends string ? R : never;

// Prettier 2.8.3 (Second format)
SyntaxError: '?' expected. 

// Prettier 2.8.4
type Foo<T> = T extends ((a) => a is infer R extends string) ? R : never;
```

</details>

<details>
<summary>vercel/turbo</summary>

### [`v1.7.4`](https://togithub.com/vercel/turbo/releases/tag/v1.7.4)

[Compare Source](https://togithub.com/vercel/turbo/compare/v1.7.3...v1.7.4)

#### What's Changed

-   publish 1.7.4 to registry by [@&#8203;Turbobot](https://togithub.com/Turbobot)
-   chore: add local and global versions in debug ([#&#8203;3661](https://togithub.com/vercel/turbo/issues/3661)) by [@&#8203;chris-olszewski](https://togithub.com/chris-olszewski)
-   chore(repo): add new labeler ([#&#8203;3684](https://togithub.com/vercel/turbo/issues/3684)) by [@&#8203;tknickman](https://togithub.com/tknickman)
-   fix: remove turborepo binary dependency on ffi ([#&#8203;3683](https://togithub.com/vercel/turbo/issues/3683)) by [@&#8203;chris-olszewski](https://togithub.com/chris-olszewski)
-   fix: Use go implementation when no build tags present ([#&#8203;3678](https://togithub.com/vercel/turbo/issues/3678)) by [@&#8203;chris-olszewski](https://togithub.com/chris-olszewski)
-   Next.js integration ci: fall back to false for force_post_to_slack ([#&#8203;3674](https://togithub.com/vercel/turbo/issues/3674)) by [@&#8203;wbinnssmith](https://togithub.com/wbinnssmith)
-   Export \__N_SSG and \__N_SSP from the error component ([#&#8203;3574](https://togithub.com/vercel/turbo/issues/3574)) by [@&#8203;alexkirsz](https://togithub.com/alexkirsz)
-   add missing workspace members and default members ([#&#8203;3668](https://togithub.com/vercel/turbo/issues/3668)) by [@&#8203;sokra](https://togithub.com/sokra)
-   ci(workflow): fix summary count error ([#&#8203;3628](https://togithub.com/vercel/turbo/issues/3628)) by [@&#8203;kwonoj](https://togithub.com/kwonoj)
-   docs: Update casing from Webpack to webpack ([#&#8203;3655](https://togithub.com/vercel/turbo/issues/3655)) by [@&#8203;wbinnssmith](https://togithub.com/wbinnssmith)
-   fix: No longer error on pnpm lockfile specifier mismatch ([#&#8203;3656](https://togithub.com/vercel/turbo/issues/3656)) by [@&#8203;chris-olszewski](https://togithub.com/chris-olszewski)
-   fix: turbo login on Windows ([#&#8203;3664](https://togithub.com/vercel/turbo/issues/3664)) by [@&#8203;chris-olszewski](https://togithub.com/chris-olszewski)
-   fix: remove quotes around extension in makefile ([#&#8203;3662](https://togithub.com/vercel/turbo/issues/3662)) by [@&#8203;chris-olszewski](https://togithub.com/chris-olszewski)
-   Import Next's CJS AsyncLocalStorage modules ([#&#8203;3634](https://togithub.com/vercel/turbo/issues/3634)) by [@&#8203;jridgewell](https://togithub.com/jridgewell)
-   ci(workflow): use release build of next-dev for integration test ([#&#8203;3650](https://togithub.com/vercel/turbo/issues/3650)) by [@&#8203;kwonoj](https://togithub.com/kwonoj)
-   docs: Increase sidebar text contrast in dark mode ([#&#8203;3625](https://togithub.com/vercel/turbo/issues/3625)) by [@&#8203;wbinnssmith](https://togithub.com/wbinnssmith)
-   Add force_post_to_slack to repository dispatch ([#&#8203;3649](https://togithub.com/vercel/turbo/issues/3649)) by [@&#8203;wbinnssmith](https://togithub.com/wbinnssmith)
-   exlcude turborepo-ffi in turbopack build ([#&#8203;3654](https://togithub.com/vercel/turbo/issues/3654)) by [@&#8203;sokra](https://togithub.com/sokra)
-   split tests into two steps, report ok and done separately ([#&#8203;3646](https://togithub.com/vercel/turbo/issues/3646)) by [@&#8203;sokra](https://togithub.com/sokra)
-   examples/basic is using PNPM, not Yarn ([#&#8203;3488](https://togithub.com/vercel/turbo/issues/3488)) by [@&#8203;ImBIOS](https://togithub.com/ImBIOS)
-   Update minor tailwind example issues. ([#&#8203;3642](https://togithub.com/vercel/turbo/issues/3642)) by [@&#8203;nathanhammond](https://togithub.com/nathanhammond)
-   add first version of rgr sandwich ([#&#8203;3306](https://togithub.com/vercel/turbo/issues/3306)) by [@&#8203;arlyon](https://togithub.com/arlyon)
-   \[docs] Fix typo: pipline => pipeline ([#&#8203;3635](https://togithub.com/vercel/turbo/issues/3635)) by [@&#8203;dtinth](https://togithub.com/dtinth)
-   Load TaskDefinitions lazily when building taskGraph ([#&#8203;3562](https://togithub.com/vercel/turbo/issues/3562)) by [@&#8203;mehulkar](https://togithub.com/mehulkar)
-   Send Next.js Integration test results to Slack ([#&#8203;3591](https://togithub.com/vercel/turbo/issues/3591)) by [@&#8203;wbinnssmith](https://togithub.com/wbinnssmith)
-   Hoist DryRunSummary fields to PackageTask ([#&#8203;3615](https://togithub.com/vercel/turbo/issues/3615)) by [@&#8203;mehulkar](https://togithub.com/mehulkar)
-   release(turborepo): 1.7.3 ([#&#8203;3627](https://togithub.com/vercel/turbo/issues/3627)) by [@&#8203;github-actions](https://togithub.com/github-actions)\[bot]
-   add helper for walking a tree concurrently and deterministic ([#&#8203;3619](https://togithub.com/vercel/turbo/issues/3619)) by [@&#8203;sokra](https://togithub.com/sokra)

**Full Changelog**: https://github.com/vercel/turbo/compare/v1.7.3...v1.7.4

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 12am and before 5am every weekday,every weekend" in timezone Asia/Kolkata, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://app.renovatebot.com/dashboard#github/timelessco/js-bottomsheet).